7.4. Меняй-удаляй (застрял на доработке ререндинга доски(7.1.5), не р…
htmlacademy-ecmascript/1839371-cinemaddict-17 pull request #13
Opened 2022-05-30 14:42 UTC by MalskyKirill

…аботает кнопка showMoreButton)

2022-05-31 18:56 UTC, ekazakov requested changes

2022-05-31 18:56 UTC, ekazakov commented on src/presenter/films-presenter.js
> +    this.#renderFilm(films);
Тут опечатка, надо `renderFilms` вызывать. Из-за этого и ошибка в консоле при клике на «show more»

2022-05-31 18:56 UTC, ekazakov commented on src/presenter/films-presenter.js
> +    const newRenderedFilmCount = Math.min(filmCount, this.#renderedFilmCount += FILM_COUNT_PER_STEP);
Тут тоже опечатка — `+=`. Надо просто `+`

2022-05-31 20:30 UTC, MalskyKirill commented on src/presenter/films-presenter.js
> +    const newRenderedFilmCount = Math.min(filmCount, this.#renderedFilmCount += FILM_COUNT_PER_STEP);
Чувствую себя л@хом(((

2022-06-01 08:50 UTC, ekazakov commented on src/presenter/films-presenter.js
> +    const newRenderedFilmCount = Math.min(filmCount, this.#renderedFilmCount += FILM_COUNT_PER_STEP);
Со всеми бывает :) Глаз замыливается и какая-нибудь мелочь может все незаметно испортить

2022-06-08 00:44 UTC, merged